version: '3.9'

name: devopsify

networks:
  devopsify-network:
    driver: bridge

services:
  app:
    container_name: devopsify-app
    build:
      context: .
      dockerfile: ./.dev/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/srv
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devopsify-network
    command: sh .dev/entrypoint.sh