FROM node:20.11-alpine

# Establece el directorio de trabajo
WORKDIR /srv

# Instala pnpm
RUN npm install -g pnpm

# Configura el entorno
ENV NODE_ENV=development

# Expone el puerto 3000
EXPOSE 3000
