version: "3.7"

services:
  STACK_PLACEHOLDER-app:
    image: IMAGE_PLACEHOLDER
    environment:
      - PORT=3000
      - DATABASE_URL="postgresql://postgres:password@STACK_PLACEHOLDER-db:5432/mydb?schema=public"
      - NEXTAUTH_URL=HOST_PLACEHOLDER
      - NEXTAUTH_SECRET=0ec4d956600492e5a0d138915644d100
    networks:
      - caddy
      - STACK_PLACEHOLDER-network
    deploy:
      replicas: 1
      labels:
        caddy: HOST_PLACEHOLDER
        caddy.tls: "TLS_PLACEHOLDER"
        caddy.tls.on_demand:
        caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  STACK_PLACEHOLDER-db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: devopsify-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - STACK_PLACEHOLDER-network
    deploy:
      replicas: 1
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  caddy:
    external: true
  STACK_PLACEHOLDER-network:
    driver: overlay

volumes:
  postgres-data: